use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "event", rename_all_fields = "PascalCase")]
pub enum Misc {
    AfmuRepairs {},
    ApproachSettlement {},
    ChangeCrewRole {},
    CockpitBreached {},
    CommitCrime {},
    Continued {},
    CrewLaunchFighter {},
    CrewMemberJoins {},
    CrewMemberQuits {},
    CrewMemberRoleChange {},
    CrimeVictim {},
    DatalinkScan {},
    DatalinkVoucher {},
    DataScanned {},
    DockFighter {},
    DockSRV {},
    EndCrewSession {},
    FighterRebuilt {},
    FuelScoop {},
    Friends {},
    JetConeBoost {},
    JetConeDamage {},
    JoinACrew {},
    KickCrewMember {},
    LaunchDrone {},
    LaunchFighter {},
    LaunchSRV {},
    ModuleInfo {},
    Music {},
    NpcCrewPaidWage {},
    NpcCrewRank {},
    Promotion {},
    ProspectedAsteroid {},
    QuitACrew {},
    RebootRepair {},
    ReceiveText {},
    RepairDrone {},
    ReservoirReplenished {},
    Resurrect {},
    Scanned {},
    SelfDestruct {},
    SendText {},
    Shutdown {},
    Synthesis {},
    SystemsShutdown {},
    USSDrop {},
    VehicleSwitch {},
    WingAdd {},
    WingInvite {},
    WingJoin {},
    WingLeave {},
    CargoTransfer {},
    SupercruiseDestinationDrop {},
}
