use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "event")]
pub enum Odyssey {
    Backpack,
    BackpackChange,
    BookDropship,
    BookTaxi,
    BuyMicroResources,
    BuySuit,
    BuyWeapon,
    CancelDropship,
    CancelTaxi,
    CollectItems,
    CreateSuitLoadout,
    DeleteSuitLoadout,
    Disembark,
    DropItems,
    DropShipDeploy,
    Embark,
    FCMaterials,
    LoadoutEquipModule,
    LoadoutRemoveModule,
    RenameSuitLoadout,
    ScanOrganic,
    SellMicroResources,
    SellOrganicData,
    SellSuit,
    SellWeapon,
    ShipLocker,
    SwitchSuitLoadout,
    TransferMicroResources,
    TradeMicroResources,
    UpgradeSuit,
    UpgradeWeapon,
    UseConsumable,
}
